# -*- coding: utf-8 -*-
"""Copy of rofy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13WMAwHqtvuuCCfzSVkoxzc0-By-lO614
"""

import pandas as pd

data = {
    "Name": ["Ali", "Sara", "Omar"],
    "Score": [85, 90, 78]
}

df = pd.DataFrame(data)
df